apiVersion: __KubernetesApi__
kind: CronJob
metadata:
  name: auto-upgrade-cronjob
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: openhorizon.org/component
                    operator: In
                    values:
                    - agent
                topologyKey: kubernetes.io/hostname
          volumes:
          - name: agent-pvc-storage
            persistentVolumeClaim:
              claimName: openhorizon-agent-pvc
          containers:
          - name: agent-auto-upgrade
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop: ["ALL"]
            image: '__ImagePath__'
            command:
              - /bin/sh
              - '-c'
              - >-
                /usr/local/bin/auto-upgrade-cronjob.sh
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /var/horizon
              name: agent-pvc-storage
              subPath: horizon
            env:
            - name: CRONJOB_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_NAMESPACE
              value:  __AgentNameSpace__
          restartPolicy: Never
          serviceAccountName: __ServiceAccount__
          serviceAccount: __ServiceAccount__