apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  -name: cluster-admin-for-namespace-scoped-agent
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"] 
  resources: ["customresourcedefinitions"]
  verbs: ["*"]