apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: __AgentNameSpace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: agent-service-account
      volumes:
      - name: agent-etc-vol
        configMap:
          name: openhorizon-agent-config
      # START_CERT_VOL
      - name: agent-cert-volume
        secret:
          secretName: openhorizon-agent-secrets
      # END_CERT_VOL
      - name: agent-pvc-storage
        persistentVolumeClaim:
          claimName: openhorizon-agent-pvc
      # START_NOT_FOR_OCP
      initContainers:
      - name: initcontainer
        image: public.ecr.aws/docker/library/alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
        command:
        - sh
        - -c
        - (chown -R 1000:1000 /horizon /policy)
        volumeMounts:
        - mountPath: /policy
          name: agent-pvc-storage
          subPath: policy
        - mountPath: /horizon
          name: agent-pvc-storage
          subPath: horizon
      # END_NOT_FOR_OCP
      containers:
      - name: anax
        image: __ImagePath__
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/default/horizon
          subPath: horizon
          name: agent-etc-vol
        # START_CERT_VOL
        - mountPath: /etc/default/cert
          name: agent-cert-volume
        # END_CERT_VOL
        - mountPath: /var/horizon
          name: agent-pvc-storage
          subPath: horizon
        - mountPath: /etc/horizon/policy.d
          name: agent-pvc-storage
          subPath: policy
        ports:
        - containerPort: 8510
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        envFrom:
          - configMapRef:
              name: openhorizon-agent-config
        env:
        - name: HZN_ORG_ID
          value: __OrgId__
        - name: AGENT_NAMESPACE
          value: __AgentNameSpace__
        - name: HZN_NAMESPACE_SCOPED
          value: __NamespaceScoped__
        - name: AGENT_CLUSTER_IMAGE_REGISTRY_HOST
          value: __ImageRegistryHost__
        # START_CERT_VOL
        - name: HZN_MGMT_HUB_CERT_PATH
          value: /etc/default/cert/agent-install.crt
        # END_CERT_VOL
